apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ideendatenbank.fullname" . }}-env
  labels: {{ include "ideendatenbank.labels" . | nindent 4 }}
type: Opaque
data:
  EDU_GUEST_USER: {{ required "config.edu.guestUser is required" .Values.config.edu.guestUser | b64enc | quote }}
  EDU_GUEST_PASS: {{ required "config.edu.guestPass is required" .Values.config.edu.guestPass | b64enc | quote }}
  {{- if and .Values.config.llm.enabled .Values.config.llm.apiKey }}
  B_API_KEY: {{ .Values.config.llm.apiKey | b64enc | quote }}
  {{- end }}
